project:
  type: website

website:
  title: "ARC-LBB"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - eda.qmd
      - autocorrelation.qmd
      - kriging.qmd
      - pca.qmd
      - multikriging.qmd
      - ml.qmd
      - conclusion.qmd
      - href: ppt.qmd
        text: Slides

      

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



