---
title: "ARC-LBB"
---

This is a website for ARC-LBB (Assessing the Risk of Crime in London Borough of Barnet) project, which was completed in part of the Data Science Accelerator programme by Office for National Statistics.

::: {.callout-important appearance="minimal"}
"Cognitivie behaviour therapy (CBT) for individuals to prevent crimes has shown to be less effective in countries with higher level of socioeconomic inequality like UK compared to countries with lesser inequality like Canada." - Crime Surveys User Conference (2024)
:::

ARC-LBB project started with a question of how much can structural elements contribute to criminal incidence. Although crime at individual level appears to be an outcome of personal behaviour, identifying environmental factors can help inform the risk of crime at population level, akin to structural determinants in population health.

Similar efforts have been recognised in crime analytics. Metropolitan Police has started to investigate Risk Terrain Modelling, which aims to identify geographical factors that correlate to specific crime type of interest.[^1] Several works have been ongoing in the academia as well.[^2][^3][^4]

[^1]: Metropolitan Police - MPS’s use of the Risk Terrain Modelling application: <https://www.met.police.uk/foi-ai/metropolitan-police/disclosure-2023/june-2023/mps-use-risk-terrain-modelling-application/>

[^2]: Cichosz - Urban Crime Risk Prediction Using Point of Interest Data: <https://www.mdpi.com/2220-9964/9/7/459>

[^3]: Shah et al - Crime forecasting: a machine learning and computer vision approach to crime prediction and prevention: <https://vciba.springeropen.com/articles/10.1186/s42492-021-00075-z>

[^4]: Yunus & Loo - London street crime analysis and prediction using crowdsourced dataset: <https://www.sciencedirect.com/science/article/pii/S2772415823000160>

```{r echo = FALSE, include = TRUE}
pacman::p_load(here, leaflet)
readRDS(here("1_data", "multi_krige_map.RDS"))
```

Sourcing publicly available crime data from Police and places data from Open Street Map, the project created geospatial and classic machine learning models to assess the risk of crime - in particular anti-social behaviour - within the borough and critically evaluated the model performance.[^5][^6]

[^5]: Police - Street-level crimes: <https://data.police.uk/docs/method/crime-street/>

[^6]: Open Street Map - Open Street Map Wiki: <https://wiki.openstreetmap.org/wiki/Main_Page>

Special thanks to my mentor MW for all the help and encouragement throughout the project.